Forc test change
FuelLabs/sway-applications pull request #297
Opened 2022-11-17 21:33 UTC by brandonsurh

## Type of change

- Documentation

## Changes

The following changes have been made:

- Changed documentation for all instances of
```
forc test
```

to be

```
forc build
cargo test
```

Changes included `README.md`s and `.docs/contributing-book/src/documentation/project-quality/testing.md` (seen below)
```
This file is the one that is called by `forc build && cargo test` and thus it only contains the modules `functions` and `utils` in order to bring them into scope so that the tests can run.
```

## Notes

- There is still one mention of `forc test` in `.github\workflows\ci.yml`.
- Snippet of code:
```
      - name: Run Forc tests
        run: |
          cd ${{ matrix.project }}
          cargo test
```

## Related Issues

Closes #286

2022-11-18 15:21 UTC, simonr0204 commented on .docs/contributing-book/src/documentation/project-quality/testing.md
> +This file is the one that is called by `forc build && cargo test` and thus it only contains the modules `functions` and `utils` in order to bring them into scope so that the tests can run.
```suggestion
This file is the entry point for the tests, and thus it contains only the modules `functions` and `utils`. This is what is executed when `cargo test` is run.
```

2022-11-18 15:22 UTC, simonr0204 requested changes

2022-11-18 15:22 UTC, simonr0204 commented on .docs/contributing-book/src/documentation/project-quality/testing.md
> +This file is the one that is called by `forc build && cargo test` and thus it only contains the modules `functions` and `utils` in order to bring them into scope so that the tests can run.
```suggestion
This file is the entry point for the tests, and thus it contains only the modules `functions` and `utils`. This is what is executed when `cargo test` is run.
```

2022-11-18 16:40 UTC, simonr0204 approved these changes

2022-11-18 16:52 UTC, simonr0204 commented
This is strange - the only files that have changed are the `.md` files, but the CI is failing to build one of the projects. I'll take a closer look later.

2022-11-21 15:53 UTC, Braqzen requested changes

2022-11-21 15:53 UTC, Braqzen commented on .docs/contributing-book/src/documentation/project-quality/testing.md
> +This file is the entry point for the tests, and thus it contains only the modules `functions` and `utils`. This is what is executed when `cargo test` is run.
```suggestion
The `harness` file is the entry point for the tests, and thus it contains the `functions` and `utils` modules. This is what is executed when `cargo test` is run.
```

2022-11-21 15:53 UTC, Braqzen commented on airdrop/README.md
> +There are two commands required to run the tests for simple-asset. This will build and test the simple-asset project.
```suggestion
There are two commands required to run the tests for the simple-asset. The first command builds the contracts and the second command runs the tests.
```

2022-11-21 15:53 UTC, Braqzen commented on airdrop/README.md
> +There are two commands required to run the tests for simple-asset. This will build and test the simple-asset project.
Note that the sentence above this describes the simple asset however that is not where all the tests are. The context above needs to be updated to make sure that all the tests are run.

2022-11-26 22:48 UTC, Braqzen approved these changes

2022-11-26 22:49 UTC, merged