Name-Registry: accept multiple assets for payment
FuelLabs/sway-applications pull request #703
Opened 2023-07-08 18:37 UTC by Braqzen

## Type of change

- New feature

## Changes

The following changes have been made:

- New functions: `set_asset()` to add a new payment method & `rate()` to check the cost
- Tests for new functions
- Adjusted `extend()` & `register()` to allow the user to specify an asset for payment

## Notes

- TODO: spec, test new functions, adjust existing calls to take contractid + tests

## Related Issues

Closes #699

2023-07-10 11:18 UTC, bitzoic reviewed
I don't believe offering the ability to pay with multiple types of tokens really enhances the application in any meaningful way. Tokens historically have been volatile and the ratio between them can fluctuate rapidly. By offering multiple token payments a user may be over or under paying by using one token over another. This is bad for UX.

Furthermore, I don't see how this is particularly relevant to an example of a domain name resolver application.

2023-07-10 11:18 UTC, bitzoic commented on name-registry/project/contracts/registry-contract/src/main.sw
> +        storage.assets.get(id).unwrap()
This will fail if I pass an invalid contract id. There should be a check for `None` before unwrapping.

2023-07-11 17:04 UTC, Braqzen commented
> I don't believe offering the ability to pay with multiple types of tokens really enhances the application in any meaningful way. Tokens historically have been volatile and the ratio between them can fluctuate rapidly. By offering multiple token payments a user may be over or under paying by using one token over another. This is bad for UX.
> 
> Furthermore, I don't see how this is particularly relevant to an example of a domain name resolver application.

You've countered your own point regarding volatility. Whether you have 1 asset or 2 makes no difference. Both are volatile.

Being able to pay for something in multiple ways is inherently an improvement. I don't think that needs an explanation.

Over / under paying isn't an issue. Pick the asset that you want. You can check the price / the app would tell you how much you are paying.

As for the last sentence, it's just an improvement to the scope of the app and not specifically the design of the registry. It's easier for people to pick this up and use it as a starting point, not that that was my reasoning for adding this in.

2023-07-11 18:44 UTC, Braqzen commented on name-registry/project/contracts/registry-contract/src/main.sw
> +    OWNER: Identity = Identity::Address(Address::from(ZERO_B256)),
After looking through the standard I've decided to not implement it in this PR.
It's a large library that requires a bunch of boilerplate code that would also needs to be tested.
The configurable is sufficient for this improvement. In the future we may raise another issue to implement the standard.

2023-07-11 20:11 UTC, Braqzen commented
Wait wtf why did the tests pass here, noooo

2023-07-12 15:36 UTC, K1-R1 requested changes
Can you update the versions in the README. Otherwise looks good

2023-07-12 15:36 UTC, K1-R1 commented on name-registry/project/contracts/registry-contract/src/main.sw
> +    /// The priviledged user with the ability to set assets for payment for the registry
```suggestion
    /// The privileged user with the ability to set assets for payment for the registry
```

2023-07-12 16:43 UTC, Braqzen commented
> Can you update the versions in the README. Otherwise looks good

Sorry, could you elaborate on why the versions need to be updated? I have not changed the versions in this PR.

2023-07-12 17:07 UTC, K1-R1 commented
> > Can you update the versions in the README. Otherwise looks good
> 
> Sorry, could you elaborate on why the versions need to be updated? I have not changed the versions in this PR.

My mistake, apologies

2023-07-12 17:09 UTC, K1-R1 approved these changes

2023-07-12 18:18 UTC, merged